### ISSUE TITLE
Include instructions for integration with eclipse

### ISSUE THREAD

**Issue by jogardi** [vietj/ceylon-maven-plugin#1]
The project worked great and really made things easier. I think it would help eclipse newbies if you included an eclipse section in the documentation that explained that they should do the following:
right click on the project and click configure>convert to ceylon.
Also, in order to run a ceylon program in eclipse you must first right click on the project and click build path. then navigate to ceylon Build>build paths. Then change the output folder at the bottom of the window from target to target/classes.  Finally, click apply.

**Comment by vietj** [comment]
I don't have much experience with maven and eclipse, is this something you could kindly contribute ?

**Comment by jogardi** [comment]
Ok. I'll do that

**Comment by vietj** [comment]
thanks!
