### ISSUE TITLE
Error compiling a program importing Maven modules

### ISSUE THREAD

**Issue by quintesse** [vietj/ceylon-maven-plugin#10]
Adding an import like `import "org.apache.camel:camel-core" "2.9.4"` to the example project's module file (https://github.com/vietj/ceylon-maven-example) and running `mvn compile` results in:

```
[INFO] --- ceylon-maven-plugin:1.2.2:compile (default) @ ceylon-maven-example ---
ERROR : Compilation error at (2,5) in /home/ceylon/tmp/mvntest/ceylon-maven-example/src/main/ceylon/com/acme/foo/module.ceylon:cannot find module artifact org.apache.camel:camel-core-2.9.4(.car|.jar)
    - dependency tree: com.acme.foo/1.0.0 -> org.apache.camel:camel-core/2.9.4
[ERROR] Compilation error at (2,5) in /home/ceylon/tmp/mvntest/ceylon-maven-example/src/main/ceylon/com/acme/foo/module.ceylon:cannot find module artifact org.apache.camel:camel-core-2.9.4(.car|.jar)
    - dependency tree: com.acme.foo/1.0.0 -> org.apache.camel:camel-core/2.9.4
```

**Comment by quintesse** [comment]
Btw, the information in this project on how to build things seems to be missing important information. For example, there is a dependency on a Maven `org.ceylon-lang:ceylon-all` artifact that I know nothing about. Where does it come from? How is it made? How does it get uploaded to Maven Central?

**Comment by quintesse** [comment]
Perhaps you know anything about this @FroMage ?

**Comment by vietj** [comment]
the org.ceylon-lang:ceylon-all (and others) is done by this project https://github.com/vietj/ceylon-maven-repo

**Comment by vietj** [comment]
can you provide a test case that exhibit the bug ?

**Comment by quintesse** [comment]
A test case how? Add a test to `it/projects`?

**Comment by quintesse** [comment]
Ok, pushed a test case.

I think the root cause is the fact that the artifact `org.ceylon-lang:com.redhat.ceylon.maven-support` is not included in `org.ceylon-lang:ceylon-all`

**Comment by vietj** [comment]
yes that was done on purpose, because it cannot work. This artifact uses a very old version of Aether that is not compatible with the common Aether versions used by Maven.

I opened an issue in Ceylon so that this part is rewritten, I think that @FroMage has done improvements there.

**Comment by quintesse** [comment]
Aha ok, understood.

**Comment by quintesse** [comment]
Ok @vietj I've been able to update the plugin to the latest 1.2.3 code and things seem to work, including compiling the test I added yesterday. (I do get 2 failing tests, but not sure if they were already failing before or not)

I also forked the https://github.com/vietj/ceylon-maven-repo and updated it to include all the new modules and such. I can create a PR for your repo but I was wondering if we shouldn't just add it to the official "ceylon" GitHub organization?

**Comment by vietj** [comment]
+1 for adding to Ceylon GitHub organization.

what are the new modules ? is there a new Ceylon release ?

**Comment by vietj** [comment]
the tests should not fail :-)

**Comment by quintesse** [comment]
> +1 for adding to Ceylon GitHub organization.

Done -> https://github.com/ceylon/ceylon-maven-repo

> what are the new modules ?

module-resolver has been split in 4 : module-resolver, m-r-aether, m-r-javascript and m-r-webdav.
There's also a new module-loader and a ceylon-cli

> is there a new Ceylon release ?

Not yet, but getting closer and I need to make sure the Maven plugin works with remote Maven repositories before we release it

> the tests should not fail :-)

Well yes I understand ;)
But I'm sure there was at least one failing even before I made any changes.

Debugging them is a bit difficult though, using `mvnDebug` doesn't seem to stop in the tests

EDIT: added "ceylon-cli" to the above list of new modules

**Comment by vietj** [comment]
you need to the maven itself in remote debug using "MAVEN_OPTS" env variable

**Comment by quintesse** [comment]
Ok, that helped!

So one of them is just due to a change in how the Runner operates I guess, instead of a log message "Could not find module: mymodule/1.0.0" it now throws a ModuleNotFoundException. Unfortunately that error gets truncated in the log so I had to check for a more generic error.

But the other I have no idea how to fix. It's the "import-dependency-force" test and if I debug it I get to line 101 of the CeylonImportDependencyMojo:

```
    result = repoSystem.resolveArtifact(repoSession, request);
```

Which then fails with an exception that it can't find the requested artifact. This is already in Maven/Aether code so I have no idea why it doesn't work, the exception doesn't give any more details. If you could perhaps take a look at that one @vietj, or give me any ideas that would be great.

**Comment by quintesse** [comment]
@vietj is there any specific reason why you implemented the `cwd` property for the plugin mojos? I have the feeling you perhaps did it to work around a certain problem?

**Comment by quintesse** [comment]
> Which then fails with an exception that it can't find the requested artifact. ... If you could perhaps take a look at that one @vietj ...

Already found the problem. The import mojo doesn't support remote repositories yet and the requested artifact (`io.netty`) wasn't on my system. I've changed it to another one (`org.jboss.modules`) that should be on any user's system if they're running the plugin.

**Comment by quintesse** [comment]
This issue has been fixed by the changes I've made to the project. Closing.

@vietj I'm pretty sure the changes will affect in some way because I've basically deprecated the `cwd` option for the Ceylon mojos. Things work more like they should now but you probably will need to fix your build files. Any help you need, just ask.

**Comment by quintesse** [comment]
@vietj we're thinking about releasing 1.2.3 "one of these days", could you please check if the changes I made to the Maven plugin are compatible with your work on Vertx? (And probably in general if we didn't break anything regarding Vertx). Thanks!
