### ISSUE TITLE
Add test targets

### ISSUE THREAD

**Issue by FroMage** [vietj/ceylon-maven-plugin#13]
We should compile tests under `src/test/ceylon`, and run them in the `test` phase.

**Comment by vietj** [comment]
I thought about this issue and the problem is to report the tests to Maven and also that it means depending on the Ceylon test module.

So something great for user, but I think requires some work

**Comment by FroMage** [comment]
Oh, you mean the Ceylon/Maven plugin must depend on the test plugin. Can we make it pull the dependency from the test module we're compiling? That will need to depend on the test module anyway. Perhaps there's a way to piggy-back on its dependency.

**Comment by FroMage** [comment]
As for reporting, `ceylon test` supports reporting options IIRC. If not we should add that.

**Comment by bjansen** [comment]
It generates TAP files, but someone opened an issue to support junit-like reports.

**Comment by tomekpiotrowski** [comment]
I wanted to start using Ceylon in one of my Maven projects and this issue is pretty much a showstopper for me.

Any chance this gets implemented in the nearest future? If not, maybe I can give it a shot?

**Comment by FroMage** [comment]
Contributions welcome, of course, but the question is mostly that if we depend on `ceylon.test` we probably have to publish it (and probably the rest of the SDK) to Maven Central.

Right now they're available in the Herd Maven repo, but I doubt you can publish plugins to Maven Central that depend on modules from other repos, can you?

**Comment by tomekpiotrowski** [comment]
According to this: https://maven.apache.org/guides/mini/guide-central-repository-upload.html it's discouraged, but possible.

**Comment by FroMage** [comment]
Does Maven actually do something special with test reports? Or is it enough to fail the build if the tests fail?

**Comment by FroMage** [comment]
Done.
