### ISSUE TITLE
Support install target

### ISSUE THREAD

**Issue by FroMage** [vietj/ceylon-maven-plugin#14]
Right now, if I do `mvn install` I get my Ceylon module compiled, but then I get an empty jar installed:

```
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/stephane/src/java-eclipse/my-app/module-ceylon/target/ceylon-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ ceylon ---
[INFO] Installing /home/stephane/src/java-eclipse/my-app/module-ceylon/target/ceylon-1.0-SNAPSHOT.jar to /home/stephane/.m2/repository/com/mycompany/app/ceylon/1.0-SNAPSHOT/ceylon-1.0-SNAPSHOT.jar
[INFO] Installing /home/stephane/src/java-eclipse/my-app/module-ceylon/pom.xml to /home/stephane/.m2/repository/com/mycompany/app/ceylon/1.0-SNAPSHOT/ceylon-1.0-SNAPSHOT.pom
```

I think we should hook into the install phase to install the compiled `.car` and probably use the `pom` that is inside the `.car`.

Which `pom.xml` to use to publish the module is tricky: the `pom.xml` written by the user doesn't need to have its dependencies correctly set, since they're declared in `module.ceylon`, but the rest of the info is valid: `groupId`, `artifactId`, etc…

The generated `pom.xml` inside the `.car` has valid dependencies but generated `groupId`/`artifactId` and such.

So ATM both are problematic. Either the plugin should verify that the dependencies are in sync. Or the compiler. The IDE could sync both files. Or we forget about syncing deps, and we add a compiler flag to point to our `pom.xml` so that it will fetch missing info from there, such as `groupId`, `artifactId`, `parent` and fill in the `dependencies` by itself.

I think that last option is saner and will lead to more correct `pom.xml` files, no?

**Comment by vietj** [comment]
why don't you use an option of the plugin to configure that ?

**Comment by FroMage** [comment]
Which option would that be?

**Comment by vietj** [comment]
when you mean install you mean install in maven repo a car file ?

**Comment by FroMage** [comment]
Yes.

**Comment by FroMage** [comment]
So the funny thing is that if I use `explodeTo` the generated `jar` is correct, even if slightly different to the `.car` because Maven adds metadata to the `MANIFEST.MF` file.

The only thing left to fix is the `pom.xml`, and for now I have added a check in the compile plugin that barfs if the dependencies list is different in the pom and Ceylon. When they are in sync, we can use the Herd Maven repo at https://modules.ceylon-lang.org/maven/1 to feed Maven modules for all the Ceylon modules to Maven.

I think this is the best way forward, but I'll need to tweak things in the Ceylon system so that:

- we remove the remaining circular deps from the distrib
- we fix the generation of `pom.xml` files (bug with `:` in `artifactId` ATM)
- we allow specification of `groupId`/`artifactId` in the `module.ceylon` if the default is not wanted
- we fix the CMR to realise that `ceylon.language` and `maven:org.ceylon-lang:ceylon.language` are one and the same (probaly hard).
- I suppose we make `ceylon.language` and the dist use the groupId allocated for Ceylon on Maven ATM

**Comment by FroMage** [comment]
Done
