### ISSUE TITLE
Do you plan to support javaScript compilation?

### ISSUE THREAD

**Issue by jogardi** [vietj/ceylon-maven-plugin#3]
I plan to use javaScript in a project so I'm wandering if there will be support for javaScript. I'm willing to add support myself but although I know maven, and the ceylon command line and understand maven plugins, I don't have hands on experience with maven plugins.

**Comment by vietj** [comment]
developing a maven plugin is not very hard :-) and I can give you advices.

and I don't see why it could not be supported. at the moment the compile mojo uses specifically the JVM compiler though.

**Comment by jogardi** [comment]
Ok. I think that I should start by pretty much copying what you did for the jvm compiler. However, I also think I should eventually add an easy way to include javaScript dependencies. Then, I think I should make it easier to include javaScript files in html pages.

**Comment by vietj** [comment]
if we can share some code between JS and Java compiler it would be a good thing.

**Comment by jogardi** [comment]
First of all, here is my plan for this:https://docs.google.com/document/d/1m3bbI5VA7DpCnKwBo2FpBHuyNg8ZbP7lLkLcmItB6lE/edit?usp=sharing
 Feel free to edit and comment.
I think most of the code in CeylonCompileMojo.java can be reused for the first things I plan to do for js support. In fact, I think I can do the first things I plan to do for js support by adding the class JsAndJavaCompiler and then changing line 112 of CeylonCompileMojo.java to use the JsAndJavaCompiler.

**Comment by jogardi** [comment]
I submitted a pull request with support for the javaScript compiler

**Comment by quintesse** [comment]
This has now been implemented. Needs the latest 1.2.3-SNAPSHOT versions of the Ceylon Maven artifacts
