### ISSUE TITLE
Choose a license, any license

### ISSUE THREAD

**Issue by jponge** [vietj/ceylon-maven-plugin#4]
:angel:

**Comment by vietj** [comment]
come on!

**Comment by jponge** [comment]
No seriously you need to explicit one :smile:

**Comment by FroMage** [comment]
+1. APL?

**Comment by vietj** [comment]
the same than usual ceylon stuff

**Comment by jponge** [comment]
ASL v2 looks good!

**Comment by vietj** [comment]
done and released a beta2 with ASL2 license.
